// mouse in menus: hover selects, click confirms, right-click backs out, wheel scrolls, menu clicks never swing the weapon
await boot(); G.give({ weapons: { longsword: 0, dagger: 0, katana: 0 } });
const E = G.sk.ev, out = [];
const ev = (type, x, y, o = {}) => E(`(() => { const r = view.getBoundingClientRect(), k = view.width / (r.width || 1);
  const cx = r.left + (ox + ${x} * scale) / k, cy = r.top + (oy + ${y} * scale) / k;
  const init = { clientX: cx, clientY: cy, button: ${o.button || 0}, buttons: 1, pointerType: 'mouse', pointerId: 1, bubbles: true, cancelable: true, deltaY: ${o.dy || 0} };
  const tgt = '${type}' === 'pointermove' ? window : view;
  if ('${type}' === 'wheel') view.dispatchEvent(new WheelEvent('wheel', init));
  else if ('${type}' === 'mousedown') view.dispatchEvent(new MouseEvent('mousedown', init));
  else tgt.dispatchEvent(new PointerEvent('${type}', init)); })()`);
const click = async (x, y, button = 0) => { ev('pointermove', x, y); G.step(1); ev('pointerdown', x, y, { button }); ev('mousedown', x, y, { button }); G.step(2); };
const M = () => E('menu ? { screen: menu.screen, sel: menu.sel, tab: menu.tab, sub: menu.sub && menu.sub.kind, pick: !!menu.pick, cat: menu.cat, isel: menu.isel, id: menu.id } : null');
G.step(10);
E("openShrineMenu({ name: 'Test Shrine' })"); G.step(2);
ev('pointermove', 69, 62 + 3 * 19 - 4); G.step(2); out.push('hover row 3 -> sel ' + M().sel);
ev('wheel', 69, 100, { dy: 100 }); G.step(1); out.push('wheel down x2 -> sel ' + M().sel);
await click(69, 62 + 2 * 19 - 4); out.push('click Flasks -> ' + M().screen);
await snap('flasks');
const fb = G.SAVE.flaskBlue; await click(205, 104); out.push(`flask ▸ blue ${fb} -> ${G.SAVE.flaskBlue}`);
await click(100, 100, 2); out.push('right-click -> ' + M().screen);
await click(69, 62 + 0 * 19 - 4); out.push('click Level Up -> ' + M().screen);
await snap('level');
await click(100, 100, 2);
await click(69, 62 + 3 * 19 - 4); out.push('click Travel -> ' + M().screen);
await snap('travel');
await click(100, 100, 2);
await click(69, 62 + 5 * 19 - 4); out.push('click Leave -> state ' + G.state + ' player ' + G.P.state);
G.step(6); out.push('after leave player state ' + G.P.state);
// Esc menu
E('openPauseMenu()'); G.step(2);
const x0 = 192 - 80 * 1.5;
await click(x0 + 3 * 80, 17); out.push('click Settings tab -> tab ' + M().tab);
ev('pointermove', 150, 44 + 3 * Math.min(17, 158 / 10) - 5); G.step(2); out.push('hover settings row 3 -> sel ' + M().sel);
await click(150, 44 + 3 * Math.min(17, 158 / 10) - 5); out.push('click Graphics -> sub ' + M().sub);
await snap('gfx');
await click(100, 100, 2); out.push('right-click -> sub ' + M().sub);
await click(x0 + 0 * 80, 17); out.push('click Equipment tab -> tab ' + M().tab);
await click(80, 51); out.push('click weapon slot -> pick ' + M().pick);
await snap('picker');
await click(18 + 1 * 20 + 9, 49 + 9); out.push('click 2nd weapon cell -> pick ' + M().pick + ' weapon ' + G.SAVE.weapon);
await click(x0 + 1 * 80, 17); out.push('click Inventory tab -> tab ' + M().tab);
await snap('inventory');
await click(100, 100, 2); out.push('right-click closes -> state ' + G.state);
G.step(6); out.push('after close player state ' + G.P.state);
return out;
