// SA: every door both ways, the one-way seals, the bookcase, and walking across the wing seams.
await boot(); G.SETTINGS.god = 1; G.grantTechniques(); G.SAVE.items.tidebreath = 1; G.SAVE.items.talon = 1;
G.SAVE.seenAreas = { thornveil: 1, barrows: 1, crimson: 1 };
const log = [], S = window.__sys;
const use = async (r, x, y) => { G.tp(r, x, y); G.step(20); G.step(1, [], ['interact']); for (let i = 0; i < 90; i++) G.step(1); return G.room; };
const walk = (r, x, y, dir, n = 200, extra = []) => { G.tp(r, x, y); G.step(10); for (let i = 0; i < n && G.room === r; i++) G.step(1, [dir, ...extra], i % 20 === 0 ? ['jump'] : []); return G.room; };
log.push('TV3 door -> ' + await use('TV3', 17, 10));
log.push('TV10 door -> ' + await use('TV10', 51, 9));
log.push('TV6 sealed door -> ' + await use('TV6', 8, 9));
log.push('TV11 door -> ' + await use('TV11', 2, 10) + ' flag ' + G.SAVE.flags['x3:TV6:seal_tv_out']);
G.step(60); log.push('TV6 door now -> ' + await use('TV6', 8, 9));
log.push('DB3 door -> ' + await use('DB3', 10, 9));
log.push('DB11 door -> ' + await use('DB11', 3, 10));
log.push('DB1 sealed -> ' + await use('DB1', 7, 13));
log.push('DB10 door -> ' + await use('DB10', 4, 9) + ' flag ' + G.SAVE.flags['x3:DB1:seal_db_out']);
G.step(60); log.push('DB1 door now -> ' + await use('DB1', 7, 13));
log.push('CM3 sealed -> ' + await use('CM3', 17, 9));
log.push('CM11 door -> ' + await use('CM11', 37, 9) + ' flag ' + G.SAVE.flags['x3:CM3:seal_cm_srv']);
G.step(60); log.push('CM3 door now -> ' + await use('CM3', 17, 9));
log.push('CM9 bookcase before -> ' + await use('CM9', 76, 6));
G.tp('CM9', 74, 6); G.step(20); G.P.face = 1; for (let i = 0; i < 4; i++) { G.step(1, [], ['attack']); G.step(30); }
log.push('bookcase flag ' + G.SAVE.flags['x3:CM9:bookcase']); G.step(60);
log.push('CM9 bookcase after -> ' + await use('CM9', 76, 6));
log.push('CM17 door -> ' + await use('CM17', 2, 12));
log.push('study door locked -> ' + await use('CM17', 7, 12));
G.SAVE.items.xsa_key1 = G.SAVE.items.xsa_key2 = G.SAVE.items.xsa_key3 = 1;
G.tp('CM17', 7, 12); G.step(20); G.step(1, [], ['interact']); G.step(60); log.push('unlock ' + G.SAVE.flags['xsa:study']);
log.push('study door -> ' + await use('CM17', 7, 12));
log.push('study back -> ' + await use('CM14', 3, 16));
// seams
log.push('TV10 west -> ' + walk('TV10', 3, 9, 'left'));
log.push('TV9 east -> ' + walk('TV9', 108, 27, 'right'));
log.push('TV11 east -> ' + walk('TV11', 44, 10, 'right'));
log.push('TV15 west -> ' + walk('TV15', 3, 10, 'left'));
log.push('TV12 east -> ' + walk('TV12', 58, 15, 'right'));
log.push('TV14 west -> ' + walk('TV14', 3, 13, 'left'));
log.push('DB11 east -> ' + walk('DB11', 44, 10, 'right'));
log.push('DB12 west -> ' + walk('DB12', 3, 12, 'left'));
log.push('DB10 east (TS) -> ' + walk('DB10', 92, 17, 'right'));
log.push('DB13 west -> ' + walk('DB13', 3, 17, 'left'));
log.push('DB15 east -> ' + walk('DB15', 36, 9, 'right'));
log.push('DB16 west -> ' + walk('DB16', 3, 9, 'left'));
log.push('CM4 window -> ' + await use('CM4', 49, 10));
log.push('CM12 window -> ' + await use('CM12', 3, 15));
log.push('CM12 tower door -> ' + await use('CM12', 44, 6));
log.push('CM10 roof door -> ' + await use('CM10', 3, 23));
log.push('CM10 east (CM11) -> ' + walk('CM10', 20, 15, 'right'));
log.push('CM11 west -> ' + walk('CM11', 3, 9, 'left'));
log.push('CM10 east low (CM13) -> ' + walk('CM10', 20, 31, 'right'));
log.push('CM13 west -> ' + walk('CM13', 3, 14, 'left'));
log.push('CM9 east -> ' + walk('CM9', 80, 22, 'right'));
log.push('CM16 west -> ' + walk('CM16', 3, 21, 'left'));
log.push('CM9 west gate shut -> ' + walk('CM9', 6, 22, 'left', 120));
G.tp('CM9', 4, 22); G.step(20); G.step(1, [], ['interact']); G.step(90);
log.push('CM9 west after lever -> ' + walk('CM9', 6, 22, 'left'));
log.push('CM5 east -> ' + walk('CM5', 50, 7, 'right'));
return log;
